development:
  adapter: mysql2
  database: bmoney_blog
  username: root
  timeout: 5000
  encoding: utf8
  reconnect: true

test:
  adapter: mysql2
  database: bmoney_blog_test
  username: root
  timeout: 5000
  encoding: utf8
  reconnect: true
